spring.application.name=webflux-mono
server.port=8074

# Deja ver en el log el nombre del hilo que atiende cada peticion.
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%15.15t]){magenta} %clr(%-40.40logger{39}){cyan} : %msg%n
logging.level.com.academymty=INFO
spring.web.error.include-message=always
